# Generated by Django 4.0.3 on 2022-03-22 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsystem',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
