# Generated by Django 4.0.3 on 2022-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LP_app', '0003_alter_allsystem_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsystem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
